// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Close
       * @returns {Promise<void>} 
       */
      "Close": () => {
        return window.go.main.App.Close();
      },
      /**
       * Maximize
       * @returns {Promise<void>} 
       */
      "Maximize": () => {
        return window.go.main.App.Maximize();
      },
      /**
       * Minimize
       * @returns {Promise<void>} 
       */
      "Minimize": () => {
        return window.go.main.App.Minimize();
      },
      /**
       * Unmaximize
       * @returns {Promise<void>} 
       */
      "Unmaximize": () => {
        return window.go.main.App.Unmaximize();
      },
    },
  },

};
export default go;
